

export default [
        {
        label:'管理员账号管理',
        to:'',
        children:[
                        {
                label:'管理员账号管理',
                to:'/admin/admins',
            },
                        {
                label:'管理员账号添加',
                to:'/admin/adminsadd',
            },
                        {
                label:'密码修改',
                to:'/admin/mod',
            },
                    ]
    },
    {
        label:'职工管理',
        to:'',
        children:[
                {
               label:'职工信息管理',
               to:'/admin/yonghu',
        },
               ]
    },
    {
        label:'前台用户管理',
        to:'',
        children:[
                {
               label:'注册用户管理',
               to:'/admin/yonghu',},
    {
               label:'添加新用户',
               to:'/admin/yonghuadd',
    },
               ]
    },
        {
        label:'馆区管理',
        to:'',
        children:[
                        {
                label:'馆区添加',
                to:'/admin/diquadd',
            },
                        {
                label:'馆区信息查询',
                to:'/admin/diqu',
            },
                    ]
    },
        {
        label:'馆区信息管理',
        to:'',
        children:[
                        {
                label:'馆区信息添加',
                to:'/admin/jingdianxinxiadd',
            },
                        {
                label:'馆区信息查询',
                to:'/admin/jingdianxinxi',
            },
                    ]
    },
       /* {
        label:'地方美食管理',
        to:'',
        children:[
                        {
                label:'美食分类添加',
                to:'/admin/meishifenleiadd',
            },
                        {
                label:'美食分类查询',
                to:'/admin/meishifenlei',
            },
                        {
                label:'地方美食添加',
                to:'/admin/difangmeishiadd',
            },
                        {
                label:'地方美食查询',
                to:'/admin/difangmeishi',
            },
                    ]
    },
        {
        label:'旅游线路管理',
        to:'',
        children:[
                        {
                label:'旅游线路添加',
                to:'/admin/lvyouxianluadd',
            },
                        {
                label:'旅游线路查询',
                to:'/admin/lvyouxianlu',
            },
                    ]
    },*/
        {
        label:'票务信息管理',
        to:'',
        children:[
                {
                        label:'馆区票务信息添加',
                        to:'/admin/ticketadd',
                    },
                    {
                        label:'馆区票务信息查询',
                        to:'/admin/ticket',
                    },
                                {
                        label:'用户票务信息查询',
                        to:'/admin/ticketinfo',
                    },
                    ]
    },
    {
        label:'预定信息管理',
        to:'',
        children:[
                        {
                label:'预定查询',
                to:'/admin/yuding',
            },
                    ]
    },
        {
        label:'新闻管理',
        to:'',
        children:[ 
                        {
                label:'分类添加',
                to:'/admin/xinwenfenleiadd',
            },
                        {
                label:'分类查询',
                to:'/admin/xinwenfenlei',
            },
                        {
                label:'新闻添加',
                to:'/admin/xinwenxinxiadd',
            },
                        {
                label:'新闻查询',
                to:'/admin/xinwenxinxi',
            },
                    ]
    },
    {
        label:'公告管理',
        to:'',
        children:[ 
                     {
                label:'公告添加',
                to:'/admin/noticeboardadd',
            },
                        {
                label:'公告查询',
                to:'/admin/noticeboard',
            },
                    ]
    },/**待实现 */
    {
        label:'活动管理',
        to:'',
        children:[ 
                {
           label:'活动信息列表',
           to:'/admin/liuyanban',
       },
               ]
    },/**待实现 */
    {
        label:'活动报名信息管理',
        to:'',
        children:[ 
                {
           label:'报名信息列表',
           to:'/admin/liuyanban',
       },
               ]
    },
    {
        label:'反馈信息管理',
        to:'',
        children:[ 
                {
           label:'反馈信息列表',
           to:'/admin/liuyanban',
       },
               ]
    },
        {
        label:'系统管理',
        to:'',
        children:[
                        {
                label:'友情链接添加',
                to:'/admin/youqinglianjieadd',
            },
                        {
                label:'友情链接查询',
                to:'/admin/youqinglianjie',
            },
                        {
                label:'轮播图添加',
                to:'/admin/lunbotuadd',
            },
                        {
                label:'轮播图查询',
                to:'/admin/lunbotu',
            },
                        
                    ]
    },
    ]
