

export default [
        {
        label:'管理员账号管理',
        to:'',
        children:[
                        {
                label:'管理员管理',
                to:'/admin/admins',
            },
                        {
                label:'添加账号',
                to:'/admin/adminsadd',
            },
                        {
                label:'修改密码',
                to:'/admin/mod',
            },
                    ]
    },
    {
        label:'职工管理',
        to:'',
        children:[
                {
               label:'信息管理',
               to:'/admin/yonghu',
        },
               ]
    },
    {
        label:'用户管理',
        to:'',
        children:[
                {
               label:'信息管理',
               to:'/admin/yonghu',},
    {
               label:'新增用户',
               to:'/admin/yonghuadd',
    },
               ]
    },
        {
        label:'馆区管理',
        to:'',
        children:[
                        {
                label:'增加馆区',
                to:'/admin/diquadd',
            },
                        {
                label:'馆区信息',
                to:'/admin/diqu',
            },
            {
                label:'增加馆内动物信息',
                to:'/admin/jingdianxinxiadd',
            },
                        {
                label:'查询馆内动物信息',
                to:'/admin/jingdianxinxi',
            },

                    ]
    },
        {
        label:'园区基本信息',
        to:'',
        children:[
                        {
                label:'信息分类添加',
                to:'/admin/meishifenleiadd',
            },
                        {
                label:'信息分类查询',
                to:'/admin/meishifenlei',
            },
                        {
                label:'信息添加',
                to:'/admin/difangmeishiadd',
            },
                        {
                label:'信息查询',
                to:'/admin/difangmeishi',
            },
                    ]
    },
      /*  {
        label:'旅游线路管理',
        to:'',
        children:[
                        {
                label:'旅游线路添加',
                to:'/admin/lvyouxianluadd',
            },
                        {
                label:'旅游线路查询',
                to:'/admin/lvyouxianlu',
            },
                    ]
    },*/
        {
        label:'票务管理',
        to:'',
        children:[
                {
                        label:'添加票务信息',
                        to:'/admin/ticketadd',
                    },
                    {
                        label:'馆区票务',
                        to:'/admin/ticket',
                    },
                                {
                        label:'查询票务信息',
                        to:'/admin/ticketinfo',
                    },
                    ]
    },
    {
        label:'预定信息管理',
        to:'',
        children:[
                        {
                label:'预定查询',
                to:'/admin/yuding',
            },
                    ]
    },
        {
        label:'新闻管理',
        to:'',
        children:[ 
                        {
                label:'添加分类',
                to:'/admin/xinwenfenleiadd',
            },
                        {
                label:'查询分类',
                to:'/admin/xinwenfenlei',
            },
                        {
                label:'添加新闻',
                to:'/admin/xinwenxinxiadd',
            },
                        {
                label:'查询新闻',
                to:'/admin/xinwenxinxi',
            },
                    ]
    },
    {
        label:'公告管理',
        to:'',
        children:[ 
                     {
                label:'添加公告',
                to:'/admin/noticeboardadd',
            },
                        {
                label:'查询公告',
                to:'/admin/noticeboard',
            }, 
                    ]
    },
    {
        label:'活动管理',
        to:'',
        children:[ 
                {
           label:'活动信息',
           to:'/admin/events',
       },{
        label:'新增活动',
        to:'/admin/eventsadd',
    },
               ]
    },
    {
        label:'活动报名信息',
        to:'',
        children:[ 
                {
           label:'报名信息管理',
           to:'/admin/registrationinfo',
       },
               ]
    },
    {
        label:'反馈信息',
        to:'',
        children:[ 
                {
           label:'反馈信息管理',
           to:'/admin/liuyanban',
       },
               ]
    },
        {
        label:'系统管理',
        to:'',
        children:[
                        {
                label:'友情链接添加',
                to:'/admin/youqinglianjieadd',
            },
                        {
                label:'友情链接查询',
                to:'/admin/youqinglianjie',
            },
                        {
                label:'轮播图添加',
                to:'/admin/lunbotuadd',
            },
                        {
                label:'轮播图查询',
                to:'/admin/lunbotu',
            },
                        
                    ]
    },
    ]
